version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: povilas1565
      MYSQL_DATABASE: insta_cat
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/insta_cat
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: povilas1565
    depends_on:
      - db

volumes:
  db_data:
